contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - prometheus-elasticsearch-exporter
    - wolfi-base
    - ca-certificates-bundle
    - busybox

accounts:
  groups:
    - groupname: elasticsearch_exporter
      gid: 65532
  users:
    - username: elasticsearch_exporter
      uid: 65532
  run-as: 65532

entrypoint:
  command: /usr/bin/elasticsearch_exporter

archs:
  - x86_64
  - aarch64
