contents:
  packages:
    # Runtime libraries of a shell are needed by helm chart As
    # currently velero doesn't have arguments to execute / pipe crd
    # updates only to kubectl alone. And we don't want to ship full
    # shell either.
    # https://github.com/vmware-tanzu/helm-charts/issues/591
    # apk info --depends busybox:
    - glibc
    - ld-linux
    - libcrypt1

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: 65532

entrypoint:
  command: "/usr/bin/velero"
