contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - chainguard-baselayout
    - ca-certificates-bundle
    - prometheus-operator

entrypoint:
  command: /usr/bin/operator

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: nonroot

archs:
  - x86_64
  - aarch64
