contents:
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
  packages:
    - alpine-baselayout-data
    - alpine-release
    - ca-certificates-bundle
    - musl

environment:
  PATH: /usr/sbin:/sbin:/usr/bin:/bin
