contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - busybox
    - powershell
    - wolfi-baselayout
accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
  run-as: root
  recursive: true
archs:
  - x86_64
  - aarch64
entrypoint:
  command: /usr/bin/pwsh
environment:
  PATH: /usr/sbin:/sbin:/usr/bin:/bin
