contents:
  # Enabling extras allows us to install packages from the Chainguard Extras repository,
  # which contains non-free software. This means Vault 1.14.8+ will be installed, which
  # are BUSL-licensed
  repositories:
    - https://packages.cgr.dev/extras
  keyring:
    - https://packages.cgr.dev/extras/chainguard-extras.rsa.pub
  packages:
    # - vault-entrypoint comes in via var.extra_packages
    # - vault comes in via var.extra_packages

accounts:
  groups:
    - groupname: vault
      gid: 65532
  users:
    - username: vault
      uid: 65532
  run-as: 0 # Entrypoint script will change user

entrypoint:
  command: /usr/bin/docker-entrypoint.sh

cmd: server -dev
