contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - chainguard-baselayout
    - ca-certificates-bundle
    - prometheus-config-reloader

entrypoint:
  command: /usr/bin/prometheus-config-reloader

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: nonroot

archs:
  - x86_64
  - aarch64

annotations:
  "org.opencontainers.image.authors": "Chainguard Team https://www.chainguard.dev/"
  "org.opencontainers.image.url": https://edu.chainguard.dev/chainguard/chainguard-images/reference/prometheus-config-reloader
  "org.opencontainers.image.source": https://github.com/chainguard-images/images/tree/main/images/prometheus-config-reloader
