# This build only runs if you add the "melange" label to a PR
on:
  pull_request:
    branches:
      - main
    types: [labeled]
jobs:
  presubmit-matrix-melange:
    if: contains(github.event.pull_request.labels.*.name, 'melange')
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - id: files
      uses: tj-actions/changed-files@ce810b29b28abf274afebdcd8fe47b8fba0f28bd # v35.9.0
      with:
        separator: ','
    - id: generate-matrix
      uses: ./.github/actions/generate-matrix
      with:
        modified-files: ${{ steps.files.outputs.all_changed_files }}
        melange-mode: only
  presubmit-build-melange:
    if: contains(github.event.pull_request.labels.*.name, 'melange')
    runs-on: ubuntu-latest
    needs: presubmit-matrix-melange
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.presubmit-matrix-melange.outputs.matrix) }}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: ./.github/actions/build-image
        with: ${{ matrix }}
  presubmit-roundup-melange:
    runs-on: ubuntu-latest
    needs: presubmit-build-melange
    steps:
      - run: |
          echo "all matrix jobs completed"
