on:
  pull_request:
jobs:
  presubmit-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
    - uses: ./.github/actions/verify-readme
      with:
        gcsBucketName: chainguard-images-build-outputs
