# This build only runs if you add the "melange" label to a PR
on:
  pull_request:
    branches:
      - main
    types: [labeled]
jobs:
  presubmit-matrix-melange:
    if: contains(github.event.pull_request.labels.*.name, 'melange')
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
    - id: files
      uses: tj-actions/changed-files@79adacd43ea069e57037edc891ea8d33013bc3da # v35.7.11
      with:
        separator: ','
    - id: generate-matrix
      uses: ./.github/actions/generate-matrix
      with:
        modified-files: ${{ steps.files.outputs.all }}
        melange-mode: only
  presubmit-build-melange:
    if: contains(github.event.pull_request.labels.*.name, 'melange')
    runs-on: ubuntu-latest
    needs: presubmit-matrix-melange
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.presubmit-matrix-melange.outputs.matrix) }}
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - uses: ./.github/actions/build-image
        with: ${{ matrix }}
  presubmit-roundup-melange:
    runs-on: ubuntu-latest
    needs: presubmit-build-melange
    steps:
      - run: |
          echo "all matrix jobs completed"
