on:
  pull_request:
jobs:
  presubmit-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - id: files
        uses: tj-actions/changed-files@b2d17f51244a144849c6b37a3a6791b98a51d86f # v35.9.2
        with:
          separator: ','
      - id: generate-matrix
        uses: ./.github/actions/generate-matrix
        with:
          modified-files: ${{ steps.files.outputs.all_changed_files }}
          melange-mode: none

  presubmit-build:
    runs-on: ubuntu-latest
    needs: presubmit-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.presubmit-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Ensure image has tests
        if: matrix.testCommandExe == ''
        run: |
          echo "Error: ${{ matrix.imageName }} image is missing tests."
          exit 1
      - uses: ./.github/actions/build-image
        with: ${{ matrix }}

  presubmit-roundup:
    needs:
      - presubmit-build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@45ce8e0eb155657ab8ccf346ade734257fd196a5 # v3.0.3

      - if: ${{ env.WORKFLOW_CONCLUSION == 'success' }}
        working-directory: /tmp
        run: echo ${{ env.WORKFLOW_CONCLUSION }} && exit 0

      - if: ${{ env.WORKFLOW_CONCLUSION == 'failure' }}
        working-directory: /tmp
        run: echo ${{ env.WORKFLOW_CONCLUSION }} && exit 1
