on:
  pull_request:
jobs:
  presubmit-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
    - id: files
      uses: tj-actions/changed-files@79adacd43ea069e57037edc891ea8d33013bc3da # v35.7.11
      with:
        separator: ','
    - id: generate-matrix
      uses: ./.github/actions/generate-matrix
      with:
        modified-files: ${{ steps.files.outputs.all }}
        melange-mode: none
  presubmit-build:
    runs-on: ubuntu-latest
    needs: presubmit-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.presubmit-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Ensure image has tests
        if: matrix.testCommandExe == ''
        run: |
          echo "Error: ${{ matrix.imageName }} image is missing tests."
          exit 1
      - uses: ./.github/actions/build-image
        with: ${{ matrix }}
  presubmit-roundup:
    runs-on: ubuntu-latest
    needs: presubmit-build
    steps:
      - run: |
          echo "all matrix jobs completed"
