on:
  pull_request:
jobs:
  presubmit-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
    - uses: ./.github/actions/verify-readme
      with:
        gcsBucketName: chainguard-images-build-outputs
