on:
  pull_request:
jobs:
  presubmit-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
    - uses: ./.github/actions/verify-readme
      with:
        gcsBucketName: chainguard-images-build-outputs
