on:
  workflow_dispatch:

jobs:
  withdraw:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: chainguard-dev/actions/setup-chainctl@main
        with:
          identity: 720909c9f5279097d847ad02a2f24ba8f59de36a/b6461e99e132298f
      - uses: imjasonh/setup-crane@v0.3
      - run: |
          for img in $(grep -v '\#' withdrawn-images.txt); do
            echo "DRY RUN: crane delete $img || true"
          done
